// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210221014022_TaskEntityAdded")]
    partial class TaskEntityAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Status");

                    b.Property<string>("TaskName");

                    b.HasKey("Id");

                    b.ToTable("TTodoList");
                });

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.HasKey("Id");

                    b.ToTable("TValue");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            DisplayName = "Walter"
                        },
                        new
                        {
                            Id = "2",
                            DisplayName = "Jackie"
                        },
                        new
                        {
                            Id = "3",
                            DisplayName = "Althea"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
