// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DisplayName");

                    b.HasKey("Id");

                    b.ToTable("TValue");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            DisplayName = "Walter"
                        },
                        new
                        {
                            Id = "2",
                            DisplayName = "Jackie"
                        },
                        new
                        {
                            Id = "3",
                            DisplayName = "Althea"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
